@host = http://localhost
@port = 5253
@token = CfDJ8NlMkeAGnq9LpYY5a5PGQhVFkG8ebbdiuWqB6ZnxhN2sIryiVu1ZAMaJ8v-CXXn756bSrXPOjSxPj_g_-ogM3MkD6ouDEnfjXtem3RLQp52u_YDZzgs9U4IGzi4-6Xj4WB_AvZ4TKGjPVGtKZidUemsz3ykXifVlVxJsmf_AUXIFBI4CPH7gOZyOmaN7WmezeDzVKzlHTr_9Lo2EpXN1MpfeoHoQaG7zZEuLHavKR_DhpTczqJdjYpylE1yQiUfA6PAbmhaIngLcoo2QuzC0WTp32uyffu9dufv9lOmhFGcIW2u5qkMd8Fa1FgcszmeKfkIDYznxCvoouxjbYRqzTOIpnlTsLXuNGpzcujtm4jc71-WtlO_H_2nitp0MU0qGdEh1tw0CyjKrsn1RR9W-ZzDWl1rE-21_qUw-Syy2ZohL38GMB9bgEAgLN9YMsc5oPjBURkU7Ec7gcq19zTRNNkAzc2o2JXihiHa4PgXKcJDm7a2aeNv7X9YPBifXvZh1KA3eMMT5OifNN8rzdvg46JzJkb-ceO-DowvNTo2giqbYCYZ7aGieGuqcgbmqXtIGWJM4LBerLGGdrqKKHTT2EvnJ_HWRMccinM077DX9IbGgMqKTP3BnHqdpbaOmdiusyEdV3UI9YuILT2VhkDHoHvbfdg-0Iexk9t6dvxnDIEqXTQrDC3Mui8-0rqp73dXqugk1C7Xkru9F7vHI6mlBxz24oCRrRWp36A6t8d1895XBtfEZ5LqtdH0Ap4V6C9VfssLnvGdnTiOWwoTzcw-zr2m9hB9A-h7jO2WmtFjoBtz8yfr6GrVv19QGuREHL0T_uj7vtI8sVW_Z00N-9DS0Z7A
@Restaurants_Api_HostAddress = {{host}}:{{port}}

GET {{Restaurants_Api_HostAddress}}/api/restaurants?pageSize=5&pageNumber=4&sortBy=Name&sortDirection=Ascending
Authorization: Bearer {{token}}
###

GET {{Restaurants_Api_HostAddress}}/api/restaurants/4/dishes
Authorization: Bearer {{token}}

###

GET {{Restaurants_Api_HostAddress}}/api/restaurants/1/dishes/2

###

GET {{Restaurants_Api_HostAddress}}/api/restaurants/3
Authorization: Bearer {{token}}
###
POST {{Restaurants_Api_HostAddress}}/api/restaurants
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Owner Restaurant 7",
    "description": "Authentic Italian pizza with fresh ingredients",
    "category": "Italian",
    "hasDelivery": true,
    "contactEmail": "info@bellaitalia.com",
    "contactNumber": "+1234567890",
    "city": "New York",
    "street": "123 Pizza Street",
    "postalCode": "10-001"
}


###
DELETE {{Restaurants_Api_HostAddress}}/api/restaurants/5
Authorization: Bearer {{token}}

###

PATCH  {{Restaurants_Api_HostAddress}}/api/restaurants/6
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "Name": "Updated restaurant by owner",
    "Description": "Authentic Italian pizza with fresh ingredients in the heart of Rome",
    "HasDelivery": true
}

###

POST {{Restaurants_Api_HostAddress}}/api/restaurants/3/dishes
Content-Type: application/json

{
    "name": "Spaghetti Bolognese",
    "description": "Classic Italian pasta dish with rich meat souce.",
    "price": 12.99,
    "kiloCalories": 800
}
###
DELETE  {{Restaurants_Api_HostAddress}}/api/restaurants/3/dishes

###

POST {{Restaurants_Api_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email": "owner@test.com",
    "password": "Admin123!"
}
###
POST {{Restaurants_Api_HostAddress}}/api/identity/register
Content-Type: application/json

{
    "email": "owner2@test.com",
    "password": "Admin123!"
}
###

PATCH  {{Restaurants_Api_HostAddress}}/api/identity/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nationality": "Serbian",
    "dateOfBirth": "2000-03-11"
}
###

POST {{Restaurants_Api_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "userEmail": "owner2@test.com",
    "RoleName": "Owner"
}
###